export const answers = [
  'Alcançou níveis ótimos de desempenho e performance…',
  'Trouxe grandes avanços sobre [problema específico].',
  'Destacou-se em desenvolver programas / estratégias que trouxeram os X resultados.',
  'Melhorou a produção em X% através da/do [atividade específica].',
  'Excedeu a meta original de X% em Y% através da [atividade específica].',
  'Acompanha continuamente a eficácia administrativa e busca melhores procedimentos, como [atividade/processo].',
  'Desenvolveu processos administrativos bem sucedidos tais como [ação] que conduziu a [resultados].',
  'Criou sistemas eficazes para recuperação de informações através de [ação].',
  'Melhorou os sistemas de suporte à gestão através da [ação].',
  'Mantém documentos organizados através de [ação] para evitar informações duplicadas.',
  'Mostra um interesse verdadeiro nos colaboradores e em encontrar soluções para seus problemas.',
  'Presta apoio e orientação aos funcionários através [ação].',
  'Usa técnicas de coaching/administração de conflitos claras para resolver problemas disciplinares.',
  'Fornece treinamento contínuo a sua equipe e parceiros.',
  'É muito respeitado pelos colaboradores por compartilhar preocupações, problemas e oportunidades.',
  'Comunica expectativas efetivamente.',
  'Destaca-se por facilitar discussões em grupo.',
  'Mantém ações de reuniões através de [ação].',
  'Comunica-se efetivamente com superiores, subordinados e membros da equipe.',
  'Reforça as políticas e valores da empresa sem criar reações negativas.',
  'Incentiva a colaboração com a equipe.',
  'Compartilha ideias e técnicas.',
  'Constrói bons relacionamentos através [ação]',
  'Demonstra espírito harmonioso e cooperativo através [ação]',
  'Gosta de compartilhar sua experiência.',
  'Busca alternativas criativas como [exemplo] que trouxe [resultados].',
  'É hábil e criativo para encontrar soluções para obstáculos.',
  'Está constantemente fazendo testes para trazer [resultados].',
  'Inicia e executa ideias criativas como [exemplo].',
  'Procura novas ideias e abordagens diferentes a [exemplo].',
  'Capacita os funcionários com a autoridade e os recursos para obter os resultados X',
  'Ajuda os subordinados a receberem visibilidade através da [ação].',
  'Incentiva os funcionários a encontrar soluções para seus problemas.',
  'Delega atividades de acordo com os pontos fortes de cada um.',
  'Delega com responsabilidade e autoridade claramente definidas.',
  'Desenvolve métodos de melhoria contínua.',
  'Concebe estratégias inovadoras.',
  'Continua a crescer e melhorar.',
  'Desenvolve meios melhores de alcançar resultados.',
  'Está continuamente planejamento melhorias.',
  'Desenvolve estratégias inovadoras como [exemplo].',
  'É inovador em situações adversas.',
  'Busca soluções inovadoras.',
  'Fomenta a curiosidade por soluções inovadoras.',
  'Promove a inovação através [exemplo].',
  'Reconhece as necessidades dos outros e auxilia a encontrar uma solução.',
  'Estabelece relações de trabalho efetivas.',
  'Busca sinergia',
  'Baseia-se na dependência mútua e compreensão.',
  'Promove a cultura empresarial entre seus colegas de trabalho.',
  'Demonstra habilidade de aprender e adaptar-se rapidamente às mudanças de situação.',
  'Compartilha experiências de aprendizado com os colegas.',
  'Promove a cultura de aprendizado.',
  'Comprometido a aprender continuamente através de [exemplo].',
  'Responde rapidamente a novas instruções, situações, métodos e procedimentos.',
  'Fornece suporte a equipe através [exemplo].',
  'Colabora com os membros da equipe para estabelecer um caminho de desenvolvimento.',
  'Mantém os funcionários responsáveis pelos próprios resultados.',
  'Fornece a equipe os recursos necessários para atingir resultados.',
  'Fornece suporte durante dos períodos de mudanças organizacionais.',
  'Desenvolve planos de ação viáveis.',
  'Cria planos flexíveis para atender as novas oportunidades.',
  'Coloca planos em ação efetivamente.',
  'Destaca-se no desenvolvimento de alternativas estratégicas.',
  'Formula eficazmente estratégias, táticas e planos de ação para impulsionar resultados X',
  'É capaz de ter um bom desempenho em uma posição de nível mais alto.',
  'Alcançou o nível necessário para ser considerado para promoção.',
  'É capaz de atuar em projetos e atividades maiores.',
  'Está fazendo um grande esforço para adquirir maior experiência e habilidades para aumentar o potencial para o crescimento.',
  'Está aumentando o potencial de crescimento através de educação e formação adicional.',
  'Exibe uma abordagem prática para resolver problemas',
  'Desenvolve soluções criativas.',
  'Transforma problemas em oportunidades.',
  'Soluciona a causa dos problemas de forma eficaz no lugar de tratar somente os sintomas.',
  'Tem habilidade em propor soluções opcionais.',
  'Excede padrões de produtividade.',
  'Produz mais do que o esperado continuamente.',
  'É um contribuinte importante para o sucesso do departamento.',
  'Realiza uma contribuição substancial para o crescimento contínuo da empresa.',
  'Excede objetivos de performance continuamente.',
  'Finalizou X projetos com X resultados.',
  'Define prazos realistas para manter os projetos em dia.',
  'É transparente com o progresso do projeto.',
  'Faz uso efetivo de todos os recursos disponíveis para um projeto.',
  'Estabelece objetivos e metas de projetos claramente.',
  'Reconhece os funcionários consistentemente.',
  'Mantém um ambiente de trabalho que estimula o crescimento individual.',
  'Assegura que os funcionários tenham uma clara compreensão de suas responsabilidades.',
  'Está prontamente disponível para apoio aos funcionários.',
  'Reconhece e lida com sinais de esgotamento dos empregados.',
  'Cumpre todos os prazos.',
  'Prepara agendas de reuniões que sejam concisas e otimizam o tempo.',
  'Mantém as entregas dentro do cronograma.',
  'Respeita o tempo dos outros.',
  'Utiliza o tempo de forma eficaz.',
  'Vive os valores da empresa com excelência.',
  'Promove forte apoio à missão e visão da empresa.',
  'É capaz de transformar visões em planos de ação concretos.',
  'Demonstra capacidade de transferir visão para execução.',
  'Destaca-se em contribuir para os objetivos da empresa.',
  'MITO. Referência no “mercado”, tem capacidade de ministrar aulas, eventos, palestras e afins sobre o assunto em questão em contextos destacados como universidade, pós graduações, MBAs, eventos de renome e etc. Ele é um Jedi',
  'Manja muito, é referência corporativa no assunto. Se fizéssemos um treinamento corporativo ele seria um dos instrutores.',
  'Domina o assunto, está se destacando na equipe e está elevando o patamar de entrega do seu projeto/área.',
  'Cumpre com consistência o item, porém ainda não é "fora da curva".',
  'Ainda tem espaço para desenvolvimento no assunto em questão.',
]
